### PR TITLE
Adding the Anorexic ruby framework to the guide

### PR DESCRIPTION
**Pull request by boazsegev**
Hi,

Please add Anorexic to the guide.

Thanks,
  Bo.

### CODE REVIEW

**Comment by leggetter** [comment]
I'd like to add your framework. However, I have concerns about the name of your framework and wouldn't be happy to have a framework with this name listed here and on my website.

Anorexia is a very serious mental illness. Somebody who is suffering from Anorexia is described as being Anorexic. See http://www.nhs.uk/conditions/Anorexia-nervosa/Pages/Introduction.aspx

I'm very sure that many people would take offence to a framework with this name so I would certainly consider changing it. If you do, please update this pull request or submit a new one and I'll accept it.

**Comment by boazsegev** [comment]
I know about the issue, very closely. Maybe because of my personal experience and my closeness to this issue, I don't find the use offending.

However, I do understand and value your viewpoint and I am now searching for alternative names. I'd appreciate any help and hope to have an update within the next few hours.

**Comment by boazsegev** [comment]
The name was updated to Plezi (meaning 'fun' in Haitian)...

I guess the tagline should change as it references the old name:

Plezi is an easy to use Ruby Websocket Framework, with full RESTful routing support and HTTP streaming support. It's name comes from the word "fun" in Haitian, since Plezi is really fun to work with and it keeps our code clean and streamlined.

**Comment by leggetter** [comment]
Merged as part of https://github.com/leggetter/realtime-web-technologies-guide/commit/d96ad7b256bdf48d0d9086cbfe1e9b9ba68ccbe8

**Pull request closed without merging**
